freebsd_instance:
  image: freebsd-12-1-release-amd64

task:
  name: FreeBSD 12
  alias: Tests
  env:
    - ARTIFACTS_DIR: artifacts
    - ARTIFACTS_HOME: ${CIRRUS_WORKING_DIR}/${ARTIFACTS_DIR}
    - BUILD_TARGET: freebsd-amd64
    - BUILD_TAG: ${CIRRUS_TAG}-${BUILD_TARGET}
    - PREFIX: /usr/local
    - GITHUB_TOKEN: ENCRYPTED[4d2ff4be4ebe39925b3dc9219341415ae606a16122e1406dd439b280b85bec6297c8c419f47f193ab5737598b99dfcb4]
  install_script:
    - pkg install -y rust gmake bash
  build_script:
    - cd wishbone-tool
    - cargo build
    - cargo build --release
  deploy_script:
    - cd wishbone-tool
    - cargo build --release
    - mkdir -p stage/${PREFIX}/bin ${ARTIFACTS_HOME}
    - cp target/release/wishbone-tool stage/${PREFIX}/bin
    - cd stage
    - tar czf ${ARTIFACTS_HOME}/wishbone-tool-${BUILD_TAG}.tar.gz *
    - ${CIRRUS_WORKING_DIR}/ci/cirrus_deploy.sh
  binaries_artifacts:
    path: ${ARTIFACTS_DIR}/*
